server:
  port: 8050

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ETicaretDB
      username: EticaretUser
      password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}